#!/usr/bin/env node
'use strict';

// Generated by scripts/generate-skill-runners.js. Do not edit directly.
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const RUNTIME_SHA256 = '40e3ee6b7ae49b42d38c95edb79e6ca586744df1ab46686b85e7fdbe857fa7f9';

function regularRuntime(file) {
  try {
    const stat = fs.lstatSync(file);
    return stat.isFile() && !stat.isSymbolicLink()
      && crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex') === RUNTIME_SHA256;
  } catch {
    return false;
  }
}

function findCliEntry(envPath) {
  const names = process.platform === 'win32'
    ? ['agentsmd.cmd', 'agentsmd.exe', 'agentsmd']
    : ['agentsmd'];
  for (const directory of envPath.split(path.delimiter)) {
    if (!directory) continue;
    for (const name of names) {
      const candidate = path.join(directory, name);
      try {
        const stat = fs.statSync(candidate);
        if (!stat.isFile()) continue;
        if (process.platform !== 'win32') fs.accessSync(candidate, fs.constants.X_OK);
        return fs.realpathSync(candidate);
      } catch {}
    }
  }
  return '';
}

function bounded(value) {
  return String(value || 'missing').slice(0, 512);
}

const skillFile = process.argv[2] || '';
const codexHome = path.resolve(process.env.CODEX_HOME || path.join(os.homedir(), '.codex'));
const candidateRoot = path.resolve(path.dirname(skillFile), '..', '..');
const standaloneRoot = path.join(codexHome, 'agentsmd');
const cliEntry = findCliEntry(process.env.PATH || '');
const cliRoot = cliEntry ? path.resolve(path.dirname(cliEntry), '..') : '';
const roots = [candidateRoot, standaloneRoot, cliRoot].filter(Boolean);
const runtime = roots
  .map((root) => path.join(root, 'scripts', 'lib', 'skill-runner.js'))
  .find(regularRuntime);

if (!runtime) {
  process.stderr.write(
    'agentsmd skill runner unavailable: skill=' + bounded(skillFile)
    + ' candidate=' + bounded(candidateRoot) + ' standalone=' + bounded(standaloneRoot)
    + ' cli=' + bounded(cliEntry)
    + '; reason=identity-matched launcher runtime missing; unblock: expose the selected plugin bundle, grant read access to the manifest-owned standalone deploy, or install the versioned agentsmd CLI\n',
  );
  process.exitCode = 1;
} else {
  process.exitCode = require(runtime).main(process.argv.slice(2), __filename, RUNTIME_SHA256);
}
